global HardMediumSoftScoreHolder scoreHolder;

// ############################################################################
// HARD constraints
// ############################################################################

rule "groupNoConflictingTasks"
	when
		Task($id : id, $group : group, $start : start, start != null, $end : getEnd())
		Task(id > $id, group == $group, start != null, !((start < $start && getEnd() < $start) || (start > $end && getEnd() > $end)))
	then
        scoreHolder.addHardConstraintMatch(kcontext, -1);
end

rule "groupNoMoreThanTwoTasksInADay"
	when
		Task($idFirst : id, start != null, $day : start.getDay(), $group : group)
		Task($idSecond : id, id > $idFirst, start != null, start.getDay() == $day, group == $group)
		Task(id > $idSecond, start != null, start.getDay() == $day, group == $group)
	then
		scoreHolder.addHardConstraintMatch(kcontext, -1);
end

rule "lunchAtCorrectTime"
	when
		Task(start != null, (start.getHour().getHourIndex() < 9 && getEnd().getHour().getHourIndex() >= 10), activity.getType() != "TeamSpirit")
	then
		scoreHolder.addHardConstraintMatch(kcontext, -1);
end

rule "lunchEnoughtTime"
	when
		Task($id : id, start != null, $day : start.getDay(), $group : group, $start : start, $end : getEnd())
		Task(id > $id, start != null, start.getDay() == $day, group == $group, (($start < start && start.getTimestampIndex() - $end.getTimestampIndex() <= 2) || ($start > start && $start.getTimestampIndex() - getEnd().getTimestampIndex() <= 2)))
	then
		scoreHolder.addHardConstraintMatch(kcontext, -1);
end

rule "instructorRequiredForTask"
	when 
		Task(start != null, instructor == null, isInstructorRequired())
	then
		scoreHolder.addHardConstraintMatch(kcontext, -1);
end

rule "instructorNotRequiredForTask"
	when 
		Task(start != null, instructor != null, !isInstructorRequired())
	then
		scoreHolder.addHardConstraintMatch(kcontext, -1);
end

rule "instructorNoConflictTasks"
	when
		Task($id : id, $start : start, $end : getEnd(), $instructor : instructor, start != null, instructor != null, $location : location)
		Task(id > $id, instructor == $instructor, !((location == $location && (start < $start && $start.getTimestampIndex()+1 - getEnd().getTimestampIndex()-1 > 0 ) || (start.getTimestampIndex()+1 - $end.getTimestampIndex()-1 > 0 && getEnd() > $end)) || (location != $location && (start < $start && $start.getTimestampIndex() - getEnd().getTimestampIndex() > 0) || (start.getTimestampIndex() - $end.getTimestampIndex() > 0 && getEnd() > $end))))
	then
		scoreHolder.addHardConstraintMatch(kcontext, -1);
end

rule "locationRequiredForTask"
	when 
		Task(start != null, location == null, isLocationRequired())
	then
		scoreHolder.addHardConstraintMatch(kcontext, -1);
end

rule "locationCorrectActivity"
	when 
		Task(start != null, location != null, location.getType() != activity.getType())
	then
		scoreHolder.addHardConstraintMatch(kcontext, -1);
end

rule "locationClimbMTBNoConflictTasks"
	when
		Task($id : id, start != null, $start : start, $end : getEnd(), location != null, $location : location, $activity : activity, (activity.getType()=="MTB" || activity.getType()=="Climb"))
		Task(id > $id, location == $location, activity == $activity, !((start < $start && $start.getTimestampIndex()+1 - getEnd().getTimestampIndex()-1 > 0 ) || (start.getTimestampIndex()+1 - $end.getTimestampIndex()-1 > 0 && getEnd() > $end)))
	then
		scoreHolder.addHardConstraintMatch(kcontext, -1);
end

rule "locationTrek1MaxFourConflictTasks"
	when
		Task($idFirst : id, start != null, $start : start, $end : getEnd(), location != null, location.getType() == "Trek", location.getTypeNumber() == 1, $location : location)
		Task(id > $idFirst, $idSecond : id, location == $location, !((start < $start && $start.getTimestampIndex() - getEnd().getTimestampIndex() >= -1 ) || (start.getTimestampIndex() - $end.getTimestampIndex() >= -1 && getEnd() > $end)))
		Task(id > $idSecond, $idThird : id, location == $location, !((start < $start && $start.getTimestampIndex() - getEnd().getTimestampIndex() >= -1 ) || (start.getTimestampIndex() - $end.getTimestampIndex() >= -1 && getEnd() > $end)))
		Task(id > $idThird, $idFourth : id, location == $location, !((start < $start && $start.getTimestampIndex() - getEnd().getTimestampIndex() >= -1 ) || (start.getTimestampIndex() - $end.getTimestampIndex() >= -1 && getEnd() > $end)))
		Task(id > $idFourth, location == $location, !((start < $start && $start.getTimestampIndex() - getEnd().getTimestampIndex() >= -1 ) || (start.getTimestampIndex() - $end.getTimestampIndex() >= -1 && getEnd() > $end)))
	then
		scoreHolder.addHardConstraintMatch(kcontext, -1);
end

rule "locationTrek23MaxTwoConflictTasks"
	when
		Task($idFirst : id, start != null, $start : start, $end : getEnd(), location != null, location.getType() == "Trek", (location.getTypeNumber() == 2 || location.getTypeNumber() == 3), $location : location)
		Task(id > $idFirst, $idSecond : id, location == $location, !((start < $start && $start.getTimestampIndex() - getEnd().getTimestampIndex() >= -1 ) || (start.getTimestampIndex() - $end.getTimestampIndex() >= -1 && getEnd() > $end)))
		Task(id > $idSecond, location == $location, !((start < $start && $start.getTimestampIndex() - getEnd().getTimestampIndex() >= -1 ) || (start.getTimestampIndex() - $end.getTimestampIndex() >= -1 && getEnd() > $end)))
	then
		scoreHolder.addHardConstraintMatch(kcontext, -1);
end

rule "activityRaftCanoeMaxThreeConflictTasks"
	when
		Task($idFirst : id, start != null, $start : start, $end : getEnd(), $activity : activity, (activity.getType()=="Raft" || activity.getType()=="Canoe"))
		Task(id > $idFirst, $idSecond : id, activity == $activity, !((start < $start && $start.getTimestampIndex() - getEnd().getTimestampIndex() >= -1 ) || (start.getTimestampIndex() - $end.getTimestampIndex() >= -1 && getEnd() > $end)))
		Task(id > $idSecond, $idThird : id, activity == $activity, !((start < $start && $start.getTimestampIndex() - getEnd().getTimestampIndex() >= -1 ) || (start.getTimestampIndex() - $end.getTimestampIndex() >= -1 && getEnd() > $end)))
		Task(id > $idThird, activity == $activity, !((start < $start && $start.getTimestampIndex() - getEnd().getTimestampIndex() >= -1 ) || (start.getTimestampIndex() - $end.getTimestampIndex() >= -1 && getEnd() > $end)))
	then
		scoreHolder.addHardConstraintMatch(kcontext, -1);
end

rule "activityArcheryMaxFourConflictTasks"
	when
		Task($idFirst : id, start != null, $start : start, $end : getEnd(), $activity : activity, activity.getType()=="Archery")
		Task(id > $idFirst, $idSecond : id, activity == $activity, !((start < $start && $start.getTimestampIndex() - getEnd().getTimestampIndex() >= -1 ) || (start.getTimestampIndex() - $end.getTimestampIndex() >= -1 && getEnd() > $end)))
		Task(id > $idSecond, $idThird : id, activity == $activity, !((start < $start && $start.getTimestampIndex() - getEnd().getTimestampIndex() >= -1 ) || (start.getTimestampIndex() - $end.getTimestampIndex() >= -1 && getEnd() > $end)))
		Task(id > $idThird, $idFourth : id, activity == $activity, !((start < $start && $start.getTimestampIndex() - getEnd().getTimestampIndex() >= -1 ) || (start.getTimestampIndex() - $end.getTimestampIndex() >= -1 && getEnd() > $end)))
		Task(id > $idFourth, activity == $activity, !((start < $start && $start.getTimestampIndex() - getEnd().getTimestampIndex() >= -1 ) || (start.getTimestampIndex() - $end.getTimestampIndex() >= -1 && getEnd() > $end)))
	then
		scoreHolder.addHardConstraintMatch(kcontext, -1);
end

rule "activityC&RHRHSTeamSpiritHRMSNoConflictTasks"
	when
		Task($id : id, start != null, $start : start, $end : getEnd(), $activity : activity, (activity.getType()=="C&R" || activity.getType()=="HRHS" || activity.getType()=="TeamSpirit" || activity.getType()=="HRMS"))
		Task(id > $id, start != null, activity == $activity, !((start < $start && getEnd() < $start) || (start > $end && getEnd() > $end)))
	then
		scoreHolder.addHardConstraintMatch(kcontext, -1);
end

// ############################################################################
// MEDIUM constraints
// ############################################################################

rule "groupNoBusOnArrivalDay"
	when
		accumulate(
			$task : Task(start != null, (isLocationRequired() && location != null && group.getHotel().isBusRequired(location)) || (!isLocationRequired() && location == null && group.getHotel().isBusRequired(activity)), start.getDay() == group.getGroupTimestampList.get(0).getDay()),
			$taskCount : count($task)
		)
	then
		scoreHolder.addMediumConstraintMatch(kcontext, (-1)*$taskCount.intValue()*$taskCount.intValue());
end

rule "instructorsMinimize"
	when
		accumulate(
			Task(start != null, getInstructor() != null, $instructor : getInstructor()),
			$instructors : collectSet($instructor)
		)
	then
		scoreHolder.addMediumConstraintMatch(kcontext, (-1)*$instructors.size()*$instructors.size()*$instructors.size());
end

// ############################################################################
// SOFT constraints
// ############################################################################

rule "additionalMorningEmployees"
	when
		$day : Day()
		$numOfGroups : Number() from accumulate($group : Group(), count($group))
		
		$morningTasks : ArrayList() from collect( Task(start != null, start.getDay() == $day, start.getHour().getHourIndex() <= 6))
		$morningReqInstructorsCount : Number() from accumulate(
			$task : Task(activity.getType() == "Climb" || activity.getType() == "C&R" || activity.getType() == "MTB" || activity.getType() == "HRHS" || activity.getType() == "TeamSpirit" || activity.getType() == "Canoe") from $morningTasks,
			count($task)
		)
		$morningFreeInstructorsCount : Number() from accumulate(
			$task : Task(activity.getType() == "Free") from $morningTasks,
			 count($task)
		)
	then
		int morningAdditionalInstructorsCount = $morningReqInstructorsCount.intValue() - ($morningFreeInstructorsCount.intValue() + ($numOfGroups.intValue() - $morningTasks.size()));
		if (morningAdditionalInstructorsCount < 0 ){
			morningAdditionalInstructorsCount = 0;
		} 
		scoreHolder.addSoftConstraintMatch(kcontext, (-1)*morningAdditionalInstructorsCount*morningAdditionalInstructorsCount);
end

rule "additionalAfternoonEmployees"
	when
		$day : Day()
		$numOfGroups : Number() from accumulate($group : Group(), count($group))
		
		$afternoonTasks : ArrayList() from collect( Task(start != null, start.getDay() == $day, start.getHour().getHourIndex() >= 9))
		$afternoonReqInstructorsCount : Number() from accumulate(
			$task : Task(activity.getType() == "Climb" || activity.getType() == "C&R" || activity.getType() == "MTB" || activity.getType() == "HRHS" || activity.getType() == "TeamSpirit" || activity.getType() == "Canoe") from $afternoonTasks,
			count($task)
		)
		$afternoonFreeInstructorsCount : Number() from accumulate(
			$task : Task(activity.getType() == "Free") from $afternoonTasks,
			 count($task)
		)
	then
		int afternoonAdditionalInstructorsCount = $afternoonReqInstructorsCount.intValue() - ($afternoonFreeInstructorsCount.intValue() + ($numOfGroups.intValue() - $afternoonTasks.size()));
		if (afternoonAdditionalInstructorsCount < 0){
			afternoonAdditionalInstructorsCount = 0;
		} 
		scoreHolder.addSoftConstraintMatch(kcontext, (-1)*afternoonAdditionalInstructorsCount*afternoonAdditionalInstructorsCount);
end

// ############################################################################
// SOFT constraints on Instructor satisfaction and fairness
// ############################################################################

rule "instructorStayAtLocation"
	when
		$instructor : Instructor()
		Task($id : id, start != null, $day : start.getDay(), $instructor == instructor, $location : location, $activity : activity, (location != null || activity.getType() == "HRHS"))
		accumulate(
		  	$task : Task(id > $id, start != null, start.getDay() == $day, instructor == $instructor, ((location != null && location != $location) || activity != $activity)),
			$instructorDifferentLocationCount : count($task)
		)
	then
		scoreHolder.addSoftConstraintMatch(kcontext, (-1)*$instructorDifferentLocationCount.intValue()*$instructorDifferentLocationCount.intValue());
end

rule "instructorStayAtLocationInOneDay"
	when
		$day : Day()
		exists Task(start != null, $day == start.getDay())
		accumulate(
			Task($id : id, start != null, $day == start.getDay(), instructor != null, $instructor : instructor, $location : location, $activity : activity, (location != null || activity.getType() == "HRHS")) &&
		  	$task : Task(id > $id, start != null, start.getDay() == $day, instructor == $instructor, ((location != null && location != $location) || activity != $activity)),
			$instructorDifferentLocationCount : count($task)
		)
	then
		scoreHolder.addSoftConstraintMatch(kcontext, (-1)*$instructorDifferentLocationCount.intValue()*$instructorDifferentLocationCount.intValue());
end

rule "instructorCompactProgram"
	when
		$instructor : Instructor()
		exists Task(start != null, instructor == $instructor)
		$instructorTasksStarts : ArrayList() from collect(Task(start != null, instructor == $instructor))
	then
		int startDayIndex = ((Task) $instructorTasksStarts.get($instructorTasksStarts.size()-1)).getStart().getDay().getDayIndex();
		int endDayIndex = ((Task) $instructorTasksStarts.get(0)).getStart().getDay().getDayIndex();
		for(int i = 0; i < $instructorTasksStarts.size(); i++){
			if(((Task) $instructorTasksStarts.get(i)).getStart().getDay().getDayIndex() < startDayIndex){
				startDayIndex = ((Task) $instructorTasksStarts.get(i)).getStart().getDay().getDayIndex();
			}
			if(((Task) $instructorTasksStarts.get(i)).getStart().getDay().getDayIndex() > endDayIndex){
				endDayIndex = ((Task) $instructorTasksStarts.get(i)).getStart().getDay().getDayIndex();
			}
		}
		int freeTime = (endDayIndex - startDayIndex + 1)*2 - $instructorTasksStarts.size();
		scoreHolder.addSoftConstraintMatch(kcontext, (-1)*freeTime*freeTime);
end

rule "groupTasksInUndesiredTime"
	when
		$group : Group()
		accumulate( 
			$task : Task(start != null, getEnd().getHour().getHourIndex() >= 21, getGroup() == $group), // >19.00
			$numOfLateEndTasks : count($task)
		)
		accumulate( 
			$task : Task(start != null, start.getHour().getHourIndex() < 1, getGroup() == $group), // <9.00
			$numOfEarlyStartTasks : count($task)
		)
		accumulate( 
			Task($id : id, start != null, group == $group, $day : start.getDay(), $start : start, $end : getEnd()) &&
			$task : Task(id > $id, start != null, getGroup() == $group, start.getDay() == $day, (start > $start && ((start.getHour().getHourIndex() - ($end.getHour().getHourIndex() + 1)) > 3)) || (start < $start && (($start.getHour().getHourIndex() - (getEnd().getHour().getHourIndex() + 1)) > 3))),
			$sumOfTimeDifferences : count($task)
		)
	then
		int total = $numOfLateEndTasks.intValue() + $numOfEarlyStartTasks.intValue() + $sumOfTimeDifferences.intValue();
		scoreHolder.addSoftConstraintMatch(kcontext, (-1)*total*total);

end

rule "groupLocationAndBusPenalty"
	when
		$group : Group()
		accumulate(
			Task(start != null, group == $group, location != null, $locationPenalty : group.getHotel().getLocationPenalty(location)),
			$groupLocationPenalty : sum($locationPenalty)
		)
		accumulate(
			$task : Task(start != null, group == $group, (isLocationRequired() && location != null && group.getHotel().isBusRequired(location)) || (!isLocationRequired() && location == null && group.getHotel().isBusRequired(activity))),
			$groupBusTransportCount : count($task)
		)
	then
		int total = $groupLocationPenalty.intValue() + $groupBusTransportCount.intValue();
		scoreHolder.addSoftConstraintMatch(kcontext, (-1)*total*total);
end